// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYckcWOK4xUcc2UtWliLThCqla72XXdiU',
    appId: '1:499788626361:web:351d4e5f42a6afdad01e68',
    messagingSenderId: '499788626361',
    projectId: 'easyqueue-mobile-4f3dd',
    authDomain: 'easyqueue-mobile-4f3dd.firebaseapp.com',
    storageBucket: 'easyqueue-mobile-4f3dd.firebasestorage.app',
    measurementId: 'G-4XRJ7WNB2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHNp4EFNtIPtja1qQR5CuXiSvEpLFq_9I',
    appId: '1:499788626361:android:d05a7751571024e9d01e68',
    messagingSenderId: '499788626361',
    projectId: 'easyqueue-mobile-4f3dd',
    storageBucket: 'easyqueue-mobile-4f3dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQl7OnOckv85FBiharKhuszMDszHWjB9A',
    appId: '1:499788626361:ios:d9c52cde5d11b4d6d01e68',
    messagingSenderId: '499788626361',
    projectId: 'easyqueue-mobile-4f3dd',
    storageBucket: 'easyqueue-mobile-4f3dd.firebasestorage.app',
    iosBundleId: 'com.example.easyqueueApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQl7OnOckv85FBiharKhuszMDszHWjB9A',
    appId: '1:499788626361:ios:d9c52cde5d11b4d6d01e68',
    messagingSenderId: '499788626361',
    projectId: 'easyqueue-mobile-4f3dd',
    storageBucket: 'easyqueue-mobile-4f3dd.firebasestorage.app',
    iosBundleId: 'com.example.easyqueueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYckcWOK4xUcc2UtWliLThCqla72XXdiU',
    appId: '1:499788626361:web:21510b9673db5ca0d01e68',
    messagingSenderId: '499788626361',
    projectId: 'easyqueue-mobile-4f3dd',
    authDomain: 'easyqueue-mobile-4f3dd.firebaseapp.com',
    storageBucket: 'easyqueue-mobile-4f3dd.firebasestorage.app',
    measurementId: 'G-J8S3P9M2LR',
  );
}
